### ISSUE TITLE
Forget phase error for Parquet file

### ISSUE THREAD

**Issue by nmadhire** [awslabs/amazon-s3-find-and-forget#228]
Hi, I am getting the below error during the forget phase of a parquet file.

```Unprocessable message: 'utf-8' codec can't decode byte 0xfc in position 7: invalid start byte```

I am only seeing this in few parquet files, please let me know if there is a way to debug this.

Thanks for your help.

**Comment by matteofigus** [comment]
Hi @nmadhire thanks for reporting the issue. Which version of S3 Find and Forget are you using?

To start troubleshooting, I recommend looking at the `ObjectUpdateFailed` log for that error and find the S3 Object to verify if it's corrupted. One thing to test is to repeat the deletion job to see if the issue is intermittent or not. If it's intermittent, it could be related to a different process writing the same object and interfering with the read. 

Another thing to try and see if there are encoding issues, is to get the S3 Object and do a query with Athena or EMR or S3 Select to see if there is any issue or if the data appears incorrectly encoded/decoded. For instance a `select * from table where "$path"="s3://path/to/object.parquet"` would do the trick in Athena or Presto EMR and you could verify you don't see some strange `?` characters on the output. 

Obviously, if you could be able to provide a minimal reproduce case here with a sample of this parquet, it would be great as we could try to reproduce and hep with a fix.

**Comment by nmadhire** [comment]
@matteofigus I am closing this issue. This was due to format misconfiguration of 1 dataset. 
Parquet forget phase is working as expected. Thanks for your help.

**Comment by matteofigus** [comment]
That's great to hear. Thanks @nmadhire
