### ISSUE TITLE
A datamapper already exists which covers this s3 location

### ISSUE THREAD

**Issue by vivek-biradar** [awslabs/amazon-s3-find-and-forget#295]
This is a bug within the code.

Scenario:
We have a datamapper created over Glue Table 1 with S3 Location : s3//mybucket/**table**
We want to create a datamapper on  Glue Table 2 with S3 Location : s3://mybucker/**table2**

We encounter this error 
![image](https://user-images.githubusercontent.com/61409872/159709750-b70ee565-da50-47b3-9e16-2cf6e54f84b7.png)

Bug : The **is_overlap** method does not check for equality of s3 locations and rather checks for substring which is incorrect

**Comment by vivek-biradar** [comment]
@matteofigus  : fyi

**Comment by matteofigus** [comment]
Hi @vivek-biradar thanks for submitting an issue.
I am not sure the `is_overlap` is wrong here. I think that if you have the first table without a final slash, it could indeed overlap with the second, and in fact if you would crawl Table 1 using a glue crawler, I am pretty sure it would crawl table2 too. I think the simplest solution here is to add a final slash in your first datamapper in the glue definition to avoid conflicts with the solution and possibly outside.

Note that in terms of glue crawler you may have this sorted using a regular expression for the matcher, is that the case? I think we only look at the location now.

**Comment by matteofigus** [comment]
My recommendation is to update the table because as explained, you may have systems like automated crawlers adding partitions that may not be able to distinguish between the 2, and for instance adding partitions for `s3://bucket/table2/partition` to both `table2` and `table`, which I think is not what you want (as you would indeed have a overlap).

You can change the location using Athena: https://docs.aws.amazon.com/athena/latest/ug/alter-table-set-location.html or using the Glue API: https://docs.aws.amazon.com/glue/latest/webapi/API_UpdateTable.html
